### ISSUE TITLE
Assignment 12, Backbone Blog

### ISSUE THREAD

**Issue by Yahsflame** [theironyard-frontend-nashville/assignments#93]
https://medium.com/@bensigal/the-jawbone-s-connected-to-the-backbone-58ab71994cf

**Comment by egdelwonk** [comment]
Can you elaborate a little more on this:

> The Method (which is not exclusive to Backbone.js) represents the way that data is handled. When a command is plugged in, method is how that particular command is handled.

**Comment by egdelwonk** [comment]
Also:

> WITH JavaScript and NOT in place of.

I get what you mean, but just to clarify, backbone IS Javascript. Meaning, it is written in Javascript. I think what you are saying is How/Why to use backbone instead of just using vanilla, plain old javascript?
