### ISSUE TITLE
Backbone blog post

### ISSUE THREAD

**Issue by ghost** [theironyard-frontend-nashville/assignments#98]
https://medium.com/@BBennett1111/a-look-at-backbone-js-793a0c329b24

**Comment by egdelwonk** [comment]
Can you comment here what you mean by this statement:

> The .Model property is really important and very powerful to building fast, efficient work within the backbone framework. Adding in models such as initialize and get add to the power and usability of the property.

**Comment by ghost** [comment]
Will,

What I meant here was that the .model property was at the heart of backbone.js and what the framework is trying to achieve. Something I understand more now is that initialize is automatically triggered by the creating a model. Sorry about the muddily nature of this section.
